### ISSUE TITLE
Errors with type ANY, and some well-formated camel cases

### ISSUE THREAD

**Issue by mxrch** [googleapis/disco-to-proto3-converter#64]
Thanks for stopping by to let us know something could be better!
#### Environment details

  - Programming language: Java
  - OS: Debian 10
  - Language runtime version: OpenJDK Runtime Environment (build 13.0.5.1+1-Debian-1)

#### Steps to reproduce

  1. Download an example Discovery Document here : https://people-pa.clients6.google.com/$discovery/rest
  2. Do `java -jar disco-to-proto3-converter-0.0.1-SNAPSHOT-jar-with-dependencies.jar --discovery_doc_path=people-pa-v2.json --output_file_path=people-pa-v2.proto`

I had 2 main errors :
1) The first one is that it doesn't like the type "ANY", it doesn't seems very popular, another discovery documents parser had the same error.. so as a workaround I changed it to a string, just to see if it pass
The full error : 
```
❯ java -jar disco-to-proto3-converter-0.0.1-SNAPSHOT-jar-with-dependencies.jar --discovery_doc_path=people-pa-v2.json --output_file_path=people-pa-v2.proto
Exception in thread "main" java.lang.IllegalArgumentException: unknown type: url
	at com.google.cloud.discotoproto3converter.disco.Schema$Type.getEnum(Schema.java:248)
	at com.google.cloud.discotoproto3converter.disco.Schema.from(Schema.java:88)
	at com.google.cloud.discotoproto3converter.disco.Schema.from(Schema.java:48)
	at com.google.cloud.discotoproto3converter.disco.Schema.from(Schema.java:71)
	at com.google.cloud.discotoproto3converter.disco.Schema.from(Schema.java:81)
	at com.google.cloud.discotoproto3converter.disco.Document.parseSchemas(Document.java:165)
	at com.google.cloud.discotoproto3converter.disco.Document.from(Document.java:72)
	at com.google.cloud.discotoproto3converter.ConverterApp.createDocument(ConverterApp.java:115)
	at com.google.cloud.discotoproto3converter.ConverterApp.convert(ConverterApp.java:54)
	at com.google.cloud.discotoproto3converter.ConverterApp.convert(ConverterApp.java:75)
	at com.google.cloud.discotoproto3converter.DiscoToProto3ConverterApp.main(DiscoToProto3ConverterApp.java:29)
```
2) Then, it doesn't like the "people_pa" because it's not in camel case, understable we can change it even if it's from official APIs :
```
Exception in thread "main" java.lang.IllegalArgumentException: Name: identifier not in NO_CHECK camel: 'people_pa'
	at com.google.cloud.discotoproto3converter.disco.Name.validateCamel(Name.java:110)
	at com.google.cloud.discotoproto3converter.disco.Name.camelInternal(Name.java:76)
	at com.google.cloud.discotoproto3converter.disco.Name.anyCamel(Name.java:58)
	at com.google.cloud.discotoproto3converter.proto3.DocumentToProtoConverter.getRpcMessageName(DocumentToProtoConverter.java:747)
	at com.google.cloud.discotoproto3converter.proto3.DocumentToProtoConverter.readResources(DocumentToProtoConverter.java:613)
	at com.google.cloud.discotoproto3converter.proto3.DocumentToProtoConverter.<init>(DocumentToProtoConverter.java:66)
	at com.google.cloud.discotoproto3converter.ConverterApp.convert(ConverterApp.java:62)
	at com.google.cloud.discotoproto3converter.ConverterApp.convert(ConverterApp.java:75)
	at com.google.cloud.discotoproto3converter.DiscoToProto3ConverterApp.main(DiscoToProto3ConverterApp.java:29)
```
But then, it gives the same error on "context.consistencyOptions.levelOptions.exactTimestamp" :
```
Exception in thread "main" java.lang.IllegalArgumentException: Name: identifier not in NO_CHECK camel: 'context.consistencyOptions.levelOptions.exactTimestamp'
	at com.google.cloud.discotoproto3converter.disco.Name.validateCamel(Name.java:110)
	at com.google.cloud.discotoproto3converter.disco.Name.camelInternal(Name.java:76)
	at com.google.cloud.discotoproto3converter.disco.Name.anyCamel(Name.java:58)
	at com.google.cloud.discotoproto3converter.proto3.DocumentToProtoConverter.schemaToField(DocumentToProtoConverter.java:401)
	at com.google.cloud.discotoproto3converter.proto3.DocumentToProtoConverter.readResources(DocumentToProtoConverter.java:642)
	at com.google.cloud.discotoproto3converter.proto3.DocumentToProtoConverter.<init>(DocumentToProtoConverter.java:66)
	at com.google.cloud.discotoproto3converter.ConverterApp.convert(ConverterApp.java:62)
	at com.google.cloud.discotoproto3converter.ConverterApp.convert(ConverterApp.java:75)
	at com.google.cloud.discotoproto3converter.DiscoToProto3ConverterApp.main(DiscoToProto3ConverterApp.java:29)
```
It only pass if I remove all the dots from the concerned identifier !

**Comment by noahdietz** [comment]
Thanks @mxrch for the issue. This isn't an officially supported Google product as mentioned in the README, and it is used for very specific purposes atm. I've downgraded to P3 with that in mind.

@vam-google any thoughts on this?

**Comment by vchudnov-g** [comment]
For technical reasons, we cannot support arbitrary `Any` fields. However, we intend to support `Any` fields where the concrete types at run-tmie are only one of the types that occur in [`error_details.proto`](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto) and when these `Any` fields only occur (at conversion time) within `error.details` fields.  PR #102 is implementing this functionailty

**Comment by daniel-sanche** [comment]
Closing due to inactivity. If this is still a problem, please re-open and we will take a look
